name: Create branch, find git tag and store in file for reuse

on:
  create:
    branches: 
      - '*t*'
      
jobs:
  get-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Create file with tag
        run: echo "${{ steps.previoustag.outputs.tag }}" > TAG.txt

      - name: Commit and push file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add TAG.txt
          git commit -m "Add TAG.txt with latest tag"
          git push
