name: Create Tag on Release Branch

on:
  create:
    branches:
      - "*Rel*"
    branches-ignore:
      - "*Rel*/*"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Create Tag
        run: |
          git config --global user.email "jt-atkins@uk.ibm.com"
          git config --global user.name "jt-atkins"
          git tag -a ${{ github.ref }} -m "Release tag"
          git push origin --tags

      - name: Print Tag Name
        run: |
          echo "Tag Name: ${{ github.ref }}"
