
on:
  create:
    # Trigger the workflow on branch creation starting with '*'
    branches:
      - '*'

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      shouldCleanup: ${{ steps.cleanup-check.outputs.shouldCleanup }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Create file with tag
        run: echo "${{ steps.previoustag.outputs.tag }}" > TAG.txt

      - name: Commit and push file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add TAG.txt
          git commit -m "Add TAG.txt with latest tag"
          git push
      - name: Check if cleanup is needed
        id: cleanup-check
        if: failure()
        run: echo "::set-output name=shouldCleanup::true"

  cleanup:
    runs-on: ubuntu-latest
    needs: get-latest-tag
    if: needs.get-latest-tag.outputs.shouldCleanup == 'true'
    steps:
      - name: Delete branch
        run: |
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.event.ref }}
