name: Create Release Candidate
on:
  create:
    branches:
      - refs/heads/rel*

jobs:
  create-release-candidate:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Existing Tag
        run: |
          tag_name=$(echo "${CI_COMMIT_REF_NAME}" | sed -e "s|refs/heads/||")-RC
          if git tag -l | grep -q "${tag_name}"; then
            echo "Deleting existing tag ${tag_name}"
            git tag -d "${tag_name}"
          fi

      - name: Create Tag
        run: |
          tag_name=$(echo "${CI_COMMIT_REF_NAME}" | sed -e "s|refs/heads/||")-RC
          git tag "${tag_name}"
          git push origin "${tag_name}"
