name: Create Tag on Release Branch

on:
  push:
    branches:
      - "*Rel*"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          
      - name: Create Tag
        run: |
          git config --global user.email "jt-atkins@uk.ibm.com"
          git config --global user.name "jt-atkins"
          git tag -a ${{ github.ref }}-RC -m "Release tag"
          git push origin ${{ github.ref }}
          
      - name: Print Tag Name
        run: |
          echo "Tag Name: ${{ github.ref }}-RC"
          
      - name: Publish Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}-RC
          release_name: Release ${{ github.ref }}-RC
          body: "This is a release for the ${{ github.ref }}-RC tag."
          token: ${{ secrets.RELEASE_TOKEN }}
