name: Create Release Branch and Tag
on:
  create:
    branches:
      - refs/heads/rel*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v2
      - name: Check Tag Name
        run: |
          tag_name=$(echo "${GITHUB_REF}" | sed -e "s|refs/heads/||")
          if git tag -l | grep -q "${tag_name}"; then
            echo "Tag already exists, deleting tag and creating new one"
            git tag -d "${tag_name}"
            git tag "${tag_name}"
          else
            echo "Creating tag"
            git tag "${tag_name}"
          fi
      - name: Push Tag to Master
        run: |
          git push origin "${tag_name}"
