name: Create Tag on Release Branch

on:
  create:
    branches:
      - "*Rel*"
    branches-from:
      - "master"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: create tag
        # You may pin to the exact commit or the version.
        # uses: nocnoc-th-devops/github-actions-create-tag@1bdaa4abc4b55b1a385289702d7507406275a828
        uses: nocnoc-th-devops/github-actions-create-tag@v0.0.4
        with:
          # GitHub token
          token: ${{ secrets.RELEASE_TOKEN }}
          # tag name
          name: Release ${{ github.ref_name }}-RC    
        
      - name: Print Tag Name
        run: |
          echo "Tag Name: ${{ github.ref }}"
