name: Extract release details

on:
  create:
    branches:
      - '*Release_*'

jobs:
  extract-release-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set user email and name
        run: |
          git config --global user.email "prince111j@gmail.com"
          git config --global user.name "Prince111j"

      - name: Initialize repository
        run: |
          git init

      - name: Fetch all tags
        run: |
          git fetch --tags

      - name: Create release tag
        run: |
          current_tag=$(git describe --tags --abbrev=0 --always)
          if [[ -z $current_tag ]]; then
            tag="v1.0.0"
          else
            major=$(echo $current_tag | cut -d. -f1)
            minor=$(echo $current_tag | cut -d. -f2)
            patch=0
            next_patch=$(($patch + 1))
            new_tag="v$major.$minor.$next_patch"
            echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
          fi
          git tag $new_tag

      - name: Create .releasedetails file
        run: |
          if [[ -f .releasedetails ]]; then
            git rm .releasedetails
          fi
          echo "${{ env.new_tag }}" > .releasedetails

      - name: Push git tag and .releasedetails file
        run: |
          git add .releasedetails
          git commit -m "Add release details"
          git push
