name: Extract release details

on:
  create:
    branches:
      - '*Release_*'

jobs:
  extract-release-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set user email and name
        run: |
          git config --global user.email "prince111j@gmail.com"
          git config --global user.name "Prince111j"

      - name: Get commit hash
        run: |
          commit_hash=$(git rev-parse HEAD)
          echo "::set-output name=commit_hash::$commit_hash"

      - name: Create .releasedetails file
        run: |
          if [[ -f .releasedetails ]]; then
            git rm .releasedetails
          fi
          echo "commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}" > .releasedetails


      - name: Push .releasedetails file
        run: |
          git add .releasedetails
          git commit -m "Add .releasedetails file"
          git push
