name: Extract release details

on:
  create:
    branches:
      - '*Release_*'

jobs:
  extract-release-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit hash
        run: |
          echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

      - name: Create .releasedetails file
        run: |
          if [[ -f .releasedetails ]]; then
            git rm .releasedetails
          fi
          echo "commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}" > .releasedetails


      - name: Push .releasedetails file
        run: |
          git add .releasedetails
          git commit -m "Add .releasedetails file"
          git push
