name: Extract release details

on:
  push:
    branches:
      - '*Release_*'

jobs:
  extract-release-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set user email and name
        run: |
          git config --global user.email "prince111j@gmail.com"
          git config --global user.name "Prince111j"

      - name: Initialize repository
        run: |
          git init

      - name: Fetch all tags
        run: |
          git fetch --tags

      - name: Check for .releasedetails file
        run: |
          if [[ -f .releasedetails ]]; then
            echo ".releasedetails file found."
            release_birth=$(cat .releasedetails)
            echo "release-birth=$release_birth" >> $GITHUB_ENV
          else
            echo ".releasedetails file not found."
          fi

      - name: Print release-birth environment variable
        run: |
          echo "release-birth=$release_birth"
