on: 
  push:
    branches: 
       - '*DEV*'
    path:
       - '**.cbl'
Job:
 Test:
   runs-on: self-hosted
   steps:
     - name: Get tag
       id: tag
       uses: dawidd6/action-get-tag@v1
       with:
           strip_v: true
         
     - name: Use tag
       run: echo ${{steps.tag.outputs.tag}}
