
on:
  create:
    # Trigger the workflow on branch creation starting with '*'
    branches:
      - '*'

jobs:
  create-and-push-tag:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create tag
      run: |
        TAG_NAME="your-tag-prefix-$(date +'%Y%m%d%H%M%S')" # Define your tag format
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create .gittag file and push
      run: |
        echo $TAG_NAME > .gittag
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .gittag
        git commit -m "Add .gittag with tag $TAG_NAME"
        git push
        - id: get_version

    - name: Get_Tag
      uses: battila7/get-version-action@v2

    - run: echo ${{ steps.get_version.outputs.version }}

    - run: echo ${{ steps.get_version.outputs.version-without-v }}
