on: 
  push:
    branches: 
       - '*DEV*'
    paths:
       - '**.cbl'
jobs:
  Get_Tag:
    runs-on: self-hosted
    steps:
       - name: Get tag
         uses: dawidd6/action-get-tag@v1

         
       - name: Use tag
         run: echo ${{steps.tag.outputs.tag}}
