on:
  create:
    branches:
      - '*'

jobs:
  create-branch-rules:
    runs-on: ubuntu-latest
#    outputs:
#      commitFailed: ${{ steps.check-failure.outputs.commitFailed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Create file with tag
        run: echo "${{ steps.previoustag.outputs.tag }}" > TAG.txt
      - name: Commit and push changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add TAG.txt
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add TAG.txt with latest tag"
            git push
          fi
          
      - name: Delete new branch on failure
        if: failure()
        env:
          GITHUB_TOKEN: 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
        run: |
          # Insert your cleanup commands here
          echo "Running cleanup due to failure in previous steps."
          # For example, delete remote branch
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs/heads/$BRANCH_NAME"

